services:
  mongodb:
    image: mongodb/mongodb-atlas-local
    hostname: mongodb
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=${MONGODB_INITDB_ROOT_USERNAME}
      - MONGODB_INITDB_ROOT_PASSWORD=${MONGODB_INITDB_ROOT_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - db:/data/db
      - configdb:/data/configdb
      - mongot:/data/mongot
volumes:
  db:
  configdb:
  mongot: